### GET /
GET http://localhost:5000

### Register
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "username": "srijani@23",
    "password": "Srijanid12@"
}

###Login
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "username": "srijani@23",
    "password": "Srijanid12@"
}